"""Per-repository template for tools/build_notebook.py (NOTEBOOK_SPEC 2.2 §4 standalone carrier).

Only the task-specific prose and stage cells live here. Runtime install, the embedded pipeline
modules (pipeline.py, samples.py, metrics.py), and the model pin/stage/verify cells are produced by
the generator from repository sources so they cannot drift from the package.

This template configures a GUIDED E2E zero-shot-classification unit ("Do Our Labels Change the Answer?"): the
pinned BART-large MNLI snapshot is digest-verified and loaded; a digest-pinned real labelled corpus (Banking77,
ten intents with readable descriptions) is fetched, validated and split; the natural-language-inference mechanism
is shown on one text-hypothesis pair; a training-fitted majority baseline and the pretrained zero-shot model are
scored on the test split; a bounded fine-tuning of the last decoder blocks and the NLI head runs in the kernel
with validation-based epoch selection; majority, pretrained and adapted systems are compared on the same held-out
messages with per-class results, confusion matrices and paired examples; a controlled activity scores the
pretrained model on the validation split under two description sets; and the adapter is exported with its
classification setup and reloaded with prediction and metric parity.

Stage-cell `md`/`code` strings go through ``str.format``: literal braces are doubled there. The header fields
(`intro`, `learning_objectives`, `exclusions`, `run_all`, `byod`, `prerequisites`) are inserted verbatim.
"""
# ruff: noqa: E501  -- markdown prose and code-cell text are kept on single lines for readable rendering

TEMPLATE = {
    "package": "bart_zero_shot_classification_pipeline",
    "repo_name": "bart-mnli-zero-shot-classification-pipeline",
    "stem": "bart_zero_shot_classification",
    "notebook_name": "bart_zero_shot_classification_colab.ipynb",
    "profile": "E2E",
    "mode": "GUIDED",
    "infrastructure_labels": True,
    "isolated_runtime": True,
    "run_all": (
        "Selecting **Run all** in a fresh supported runtime installs the pinned dependencies, stages and digest-verifies the "
        "pinned BART-large MNLI snapshot (safetensors, 1.6 GB), fetches the two digest-pinned Banking77 CSV files (1.1 MB, "
        "no credential), keeps ten intents and draws 400 / 100 / 200 balanced training, validation and test messages from "
        "the release's own partition, shows one text-hypothesis pair and the inference contract, scores a training-fitted "
        "majority baseline and the pretrained zero-shot model on the test messages, runs a bounded fine-tuning of the last "
        "two decoder blocks and the NLI head with validation-based epoch selection, compares the three systems on the same "
        "held-out messages with per-class results, confusion matrices and paired examples, scores the **pretrained** model "
        "on the validation messages under two category-description sets, exports the adapter with its classification setup "
        "and reloads it to check prediction and metric parity. The default path needs no repository clone, no DIMER worker "
        "or service, no credential, no upload dialog and no configuration edit (NOTEBOOK_SPEC 2.2 §5). A CUDA runtime is "
        "used automatically when present; on CPU the model stages take roughly ten minutes after the downloads."
    ),
    "byod": (
        "After the default path completes, set `USE_BYOD = True` in Section 4 and re-run from that cell to supply your own "
        "labelled texts as a CSV (columns `id`, `text`, `label`), a JSON array or a JSONL file of `{id, text, label}` records "
        "with 2..32 distinct labels. In this contract the **label is the category description** the model reads (for "
        "example `a refund request`), so write each as a short readable phrase and keep it identical across records; it "
        "serves as the stable category identifier too. Your records pass through the same validation, seeded stratified "
        "text-disjoint split into training, validation and test roles, baseline, fine-tuning, held-out evaluation, "
        "inference, artifact export and reload-parity cells as the Banking77 sample. Reference labels are required: the "
        "contract refuses unlabelled records, so qualitative exploration without labels uses the `classify` call in "
        "Section 5 on your own texts instead, with no accuracy or F1 reported. The category-wording activity needs a "
        "second reviewed description set and is skipped for BYOD. Uploaded files stay inside this runtime. BYOD is "
        "optional and never part of the default path."
    ),
    "pipeline_class": "BARTZeroShotClassificationPipeline",
    "weights_key": "bart-large-mnli",
    "modules": ["pipeline.py", "samples.py", "metrics.py"],
    "entry_module": "pipeline.py",
    "identity_names": {},
    "runtime_imports": ["torch", "transformers"],
    "title": "DIMER Notebook: Zero-Shot Text Classification — Do Our Labels Change the Answer?",
    "badges": [
        (
            "GitHub",
            "https://img.shields.io/badge/GitHub-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/kurtvalcorza/bart-mnli-zero-shot-classification-pipeline",
        ),
        (
            "Open In Colab",
            "https://colab.research.google.com/assets/colab-badge.svg",
            "https://colab.research.google.com/github/kurtvalcorza/bart-mnli-zero-shot-classification-pipeline/blob/main/tutorials/bart_zero_shot_classification_colab.ipynb",
        ),
        (
            "Hugging Face",
            "https://img.shields.io/badge/%F0%9F%A4%97%20Hugging%20Face-facebook%2Fbart--large--mnli-ffcc4d?style=flat",
            "https://huggingface.co/facebook/bart-large-mnli",
        ),
        (
            "Upstream",
            "https://img.shields.io/badge/Upstream-facebookresearch%2Ffairseq-181717?style=flat&logo=github&logoColor=white",
            "https://github.com/facebookresearch/fairseq/tree/main/examples/bart",
        ),
        ("arXiv", "https://img.shields.io/badge/arXiv-1910.13461-b31b1b.svg", "https://arxiv.org/abs/1910.13461"),
    ],
    "capability": "zero-shot text classification by NLI entailment (one text, a caller-supplied label set, one entailment-derived score per label, sorted; single-label softmax across labels or independent multi-label scores) and bounded supervised fine-tuning of the last decoder blocks and the NLI head on a labelled-text dataset, using the pinned BART-large MNLI weights",
    "intro": (
        "**Driving question: can changing how we describe a category change the model's decision?** This self-paced "
        "**Level 2 — Applied tasks** unit needs basic Python and Colab familiarity and no prior machine-learning "
        "experience. A realistic use: routing customer-support messages to the right team when you can name the teams' "
        "topics but have few or no labelled examples.\n\n"
        "**Input → Model → Output:** one text plus a list of candidate **category descriptions** → a pretrained "
        "natural-language-inference (NLI) model → one score per category and a predicted category. Each description is "
        "written into a statement such as *\"This customer message is about a lost or stolen card.\"*, the model judges "
        "whether that statement follows from the text, and the category whose statement is most strongly supported wins. "
        "**The category descriptions are part of the model input** — change their wording and the scores can change.\n\n"
        "**Zero-shot does not mean untrained.** The 407 M-parameter BART-large model was pretrained on large text corpora "
        "and then fine-tuned upstream on MultiNLI, a labelled natural-language-inference dataset. \"Zero-shot\" describes "
        "this notebook's task: the pretrained model classifies the banking messages using only the category descriptions, "
        "without any training on this task's examples. It says nothing about whether related text appeared in pretraining. "
        "Later the notebook adapts the model with labelled training messages; **task-adapted results are no longer "
        "zero-shot for that task**.\n\n"
        "**Scores are not probabilities of being right.** In the default single-label mode the scores are a softmax over "
        "the entailment evidence across the supplied categories: they sum to one and rank the categories, but they are "
        "not calibrated probabilities of correctness. **The score is an entailment-derived softmax, not a calibrated "
        "probability**, the **default decision rule is `argmax`**, and no threshold is shipped. **A single-label "
        "classifier always picks one of the supplied categories: it does not recognise that none of them applies.** "
        "Multi-label mode (shown once in Section 5) scores each category independently instead; the learning task here "
        "stays single-label.\n\n"
        "**How to use this notebook.** Choose a runtime (a GPU runtime is faster; CPU works), then **Runtime → Run all**. "
        "Sections 1–3 are **infrastructure** — install, carried code and model verification — and can be run without "
        "study. The learning path starts in Section 4. Form fields (`# @param`) are the only values meant to be edited; "
        "the defaults reproduce the recorded path. Each stage states its question, asks you to **predict** before it runs, "
        "and ends with **What to notice**; collapsible hints give worked answers. Completion records are **optional "
        "personal notes and are not required submissions**.\n\n"
        "**Roadmap:** 4 inspect the categories and messages → 5 see how zero-shot NLI scores one message → 6 majority "
        "baseline and pretrained model on held-out messages → 7 adapt the model with labelled examples → 8 compare the "
        "three systems → 9 interpret paired changes → 10 **change one thing: the category wording** → 11 export and reload "
        "→ conclude.\n\n"
        "**Data:** Banking77 (Casanueva et al., 2020; CC BY 4.0), 13,083 customer-support messages over 77 banking intents, "
        "of which this notebook keeps ten, each with a stable intent ID and a readable description. Evidence here comes "
        "from one seeded split of one corpus with no dispersion estimate; it describes this sample, not your categories."
    ),
    "learning_objectives": (
        "by the end you should be able to (1) explain *text + candidate category descriptions → model → category scores "
        "and prediction*; (2) explain how zero-shot classification works through natural-language inference; (3) "
        "distinguish zero-shot inference from task-specific adaptation; (4) compare a majority baseline, the pretrained "
        "model and the adapted model on the same held-out messages; (5) measure how sensitive predictions are to category "
        "wording through a controlled experiment; and (6) interpret accuracy, macro-F1, per-class results, confusion "
        "patterns and the limits of this evidence."
    ),
    "exclusions": (
        "a trained classification head over a fixed label vocabulary (the adapted model is still an NLI scorer over any "
        "label set), recognising that no supplied category applies, text generation or summarisation (the "
        "`bart-cnn-summarization-pipeline` sibling covers that), natural-language inference on caller-built "
        "premise/hypothesis pairs as a product feature, sentence embeddings, token-level tagging, full-model or encoder "
        "fine-tuning, non-English text, any calibrated probability, general robustness to wording, and any claim that a "
        "Banking77 split stands in for your label set. The repository exposes none of these."
    ),
    "prerequisites": [
        "- **Learner:** basic Python and Colab familiarity; no prior machine-learning experience. New terms (entailment, baseline, macro-F1, confusion matrix, adaptation) are explained where they are first used.",
        "- **Runtime:** a fresh supported runtime (Google Colab or Jupyter, Python 3.12). The default path runs on CPU (float32) and uses CUDA automatically when available. The pinned `torch==2.14.0` install and the 1.6 GB checkpoint are the large downloads. On CPU, classifying one message over ten categories takes about 0.3 s and one training epoch over 800 NLI pairs about a minute; a GPU is much faster.",
        "- **Data contract:** records are `{id, text, label}` — a message and the description of its reference category — the text 1..8,000 characters and, paired with the longest hypothesis, at most 1,024 BPE tokens at inference, the label 1..100 characters, 2..32 distinct labels, ids matching `[A-Za-z0-9_.:-]{1,64}` and unique; a dataset needs 8..20,000 records; texts are de-duplicated case-insensitively before splitting so the same message never sits in two splits.",
        "- **Truncation:** inference never truncates — a message whose pair with a hypothesis exceeds 1,024 tokens is rejected with a `ValueError` naming the count. During **training only**, each pair is cut at 256 tokens; a cut can remove the decisive words of a long message, so long-document classification is out of scope. Banking77 messages are short, and Section 6 prints the longest pair actually scored.",
        "- **Validation is structural, not semantic:** nothing checks that a description fits its messages or that the categories are mutually exclusive — a mislabelled corpus is fine-tuned on without complaint, and a description the model cannot read as English will score badly zero-shot.",
        "- **Privacy:** Do not upload confidential or restricted data to a hosted runtime unless you are authorized to process it there — a customer-support log with its intent labels is exactly that. The default path uploads nothing.",
        "- **External access (data):** besides the Hub, the default path fetches two pinned objects (`train.csv` 839,073 bytes, SHA-256 `b06e26ac…`; `test.csv` 239,961 bytes, SHA-256 `d12d6e3b…`) from `raw.githubusercontent.com` at the pinned `PolyAI-LDN/task-specific-datasets` commit over HTTPS, each refused on any mismatch before it is read; Banking77 is CC BY 4.0 (attribution: PolyAI; Casanueva et al., 2020).",
    ],
    "cells": [
        {
            "md": (
                "## 4. Inspect the categories and messages\n\n"
                "**Input:** the pinned Banking77 files. **System:** download verification, filtering to ten intents, "
                "de-duplication and a seeded balanced split. **Output:** training, validation and test messages, each with "
                "a stable **category ID** (the Banking77 intent) and a readable **description** the model will read.\n\n"
                "`fetch_corpus` refuses a byte-size or SHA-256 mismatch before parsing; `read_corpus` checks columns, row "
                "counts and the 77 intents; `build_sample_dataset` keeps the ten intents in `LABEL_SET`, maps each to its "
                "description, drops repeated messages and draws **balanced** seeded samples — 40 training and 10 "
                "validation messages per category from `train.csv` (disjoint), 20 test messages per category from "
                "`test.csv`, the release's own partition. `validate_dataset` checks every record, `check_split_disjoint` "
                "asserts no message appears in two splits, and four refusal probes show the contract rejecting bad input "
                "before any model runs.\n\n"
                "The three **roles** stay separate for the whole notebook: training messages fit the baseline and the "
                "adaptation; validation messages choose the training epoch and host the wording activity; test messages "
                "are used only to report the final comparison.\n\n"
                "**Predict before running:** read the ten descriptions in the output. Which two do you expect the model to "
                "confuse most often, and why? Keep your answer — Section 8's confusion matrix tests it."
            ),
            "code": (
                "import hashlib\n"
                "import io\n"
                "import json\n"
                "from collections import Counter\n\n"
                "USE_BYOD = False  # @param {{type:\"boolean\"}}\n"
                "SPLIT_SEED = 42  # @param {{type:\"integer\"}}\n"
                "TEMPLATE = 'This customer message is about {{}}.'  # @param {{type:\"string\"}}\n\n"
                "os.makedirs('outputs', exist_ok=True)\n"
                "if USE_BYOD:\n"
                "    from google.colab import files\n"
                "    uploaded = files.upload()\n"
                "    file_name, payload = next(iter(uploaded.items()))\n"
                "    byod_path = Path('work') / file_name\n"
                "    byod_path.parent.mkdir(parents=True, exist_ok=True)\n"
                "    byod_path.write_bytes(payload)\n"
                "    records = load_byod_dataset(byod_path)\n"
                "    splits = split_dataset(records, seed=SPLIT_SEED)\n"
                "    data_source = 'BYOD (' + file_name + ')'\n"
                "    raw_rows = {{'byod': len(records)}}\n"
                "else:\n"
                "    corpus = read_corpus(fetch_corpus(cache_dir='weights/banking77'))\n"
                "    raw_rows = {{name: len(part) for name, part in corpus.items()}}\n"
                "    splits = build_sample_dataset(corpus, seed=SPLIT_SEED)\n"
                "    data_source = f'{{CORPUS_NAME}} ({{CORPUS_RELEASE}}; {{CORPUS_LICENSE}}), {{len(LABEL_SET)}} of {{CORPUS_INTENTS}} intents'\n"
                "train_records, val_records, test_records = splits['train'], splits['validation'], splits['test']\n"
                "dataset_manifests = {{name: validate_dataset(part) for name, part in splits.items()}}\n"
                "labels = label_names(train_records)\n"
                "disjoint = check_split_disjoint(splits)\n"
                "write_dataset_csv(train_records, 'outputs/{stem}_train.csv')\n"
                "# Stable category IDs and their descriptions (set A). For BYOD the description is its own ID.\n"
                "CATEGORIES = [{{'id': intent, 'description': phrase}} for intent, phrase in LABEL_SET.items()] if not USE_BYOD else [{{'id': label, 'description': label}} for label in labels]\n"
                "print({{'data_source': data_source, 'raw_rows': raw_rows, 'splits': disjoint, 'file_sha256': {{k: v[2][:12] + '...' for k, v in CORPUS_FILES.items()}}}})\n"
                "counts = {{name: Counter(r['label'] for r in part) for name, part in splits.items()}}\n"
                "print(f\"{{'category ID':38}} {{'description (set A)':42}} train  val  test\")\n"
                "for category in CATEGORIES:\n"
                "    d = category['description']\n"
                "    print(f\"{{category['id']:38}} {{d:42}} {{counts['train'][d]:5}} {{counts['validation'][d]:4}} {{counts['test'][d]:5}}\")\n"
                "for name, manifest in dataset_manifests.items():\n"
                "    print({{name: {{'n': manifest['n_records'], 'unique_texts': manifest['unique_texts'], 'text_chars': manifest['text_chars'], 'digest': manifest['digest'][:16] + '...'}}}})\n"
                "print('One training message per category (the first in split order):')\n"
                "for category in CATEGORIES:\n"
                "    example = next(r for r in train_records if r['label'] == category['description'])\n"
                "    print(f\"  [{{category['description']}}] {{example['text'][:100]}}\")\n\n"
                "probes = {{\n"
                "    'duplicate id': [{{**r, 'id': 'same'}} for r in train_records[:8]],\n"
                "    'label outside the label set': ([{{**train_records[0], 'label': 'something else'}}, *train_records[1:8]], labels),\n"
                "    'missing field': [{{'id': r['id'], 'text': r['text']}} for r in train_records[:8]],\n"
                "    'too small': train_records[:3],\n"
                "}}\n"
                "for name, probe in probes.items():\n"
                "    try:\n"
                "        validate_dataset(probe[0], labels=probe[1]) if isinstance(probe, tuple) else validate_dataset(probe)\n"
                "        print({{'probe': name, 'verdict': 'accepted'}})\n"
                "    except (TypeError, ValueError) as exc:\n"
                "        print({{'probe': name, 'rejected': str(exc)[:110]}})"
            ),
        },
        {
            "md": (
                "**What to notice:** 400 / 100 / 200 messages with 40 / 10 / 20 per category, three dataset digests, no "
                "message shared between splits, and four refusals. Some messages are genuinely **ambiguous**: *\"my card "
                "still hasn't come, could it have been stolen?\"* touches both *card arrival* and *a lost or stolen card*, "
                "and a failed top-up may mention a declined payment. The reference label records what the annotator "
                "decided; a model that picks the other plausible category is scored wrong. Reading a few examples per "
                "category is the fastest check that descriptions match the data.\n\n"
                "## 5. How zero-shot classification scores one message\n\n"
                "The model never sees a list of labels. For every candidate category it reads a **text-hypothesis pair**: "
                "the message (the *premise*) and a statement built from the template, *\"This customer message is about "
                "[description].\"* (the *hypothesis*). For each pair the NLI head produces three logits — **entailment** "
                "(the statement follows from the message), **neutral** (the message neither supports nor rules it out) and "
                "**contradiction** (the message rules it out). Single-label classification keeps only the entailment "
                "logit of every pair and applies a softmax across the categories, so the scores compete and sum to one; "
                "neutral and contradiction evidence affect the result only through the entailment logit the model "
                "assigns. Multi-label classification instead turns each pair's [contradiction, entailment] logits into an "
                "independent score per category.\n\n"
                "The next cell shows this for one training message: its reference description and one other description, "
                "with the three logits per pair, then the ranked single-label scores over all ten categories. Below that, "
                "the inference contract is exercised as before on three synthetic sentences: `validate_inputs` applies "
                "the same checks `classify` applies and returns an input manifest; the pair-token ceiling `MAX_TEXT_TOKENS` "
                "is enforced inside `classify`, which **rejects with a `ValueError` naming the count, never truncates**; "
                "and a duplicate-label probe is recorded as a finding.\n\n"
                "**Predict before running:** for the first message, which category do you expect to win, and will the "
                "wrong description get a large *contradiction* logit or a large *neutral* one?"
            ),
            "code": (
                "import time\n\n"
                "MULTI_LABEL = False  # @param {{type:\"boolean\"}}\n\n"
                "example = train_records[0]\n"
                "other = next(label for label in labels if label != example['label'])\n"
                "pair_view = pipe.classify(example['text'], [example['label'], other], multi_label=True, hypothesis_template=TEMPLATE)\n"
                "print('Premise:', example['text'])\n"
                "for entry in pair_view['labels']:\n"
                "    print({{'hypothesis': TEMPLATE.format(entry['label']), 'entailment': round(entry['entailment_logit'], 2), 'neutral': round(entry['neutral_logit'], 2), 'contradiction': round(entry['contradiction_logit'], 2), 'independent_score': round(entry['score'], 3)}})\n"
                "ranked = pipe.classify(example['text'], labels, hypothesis_template=TEMPLATE)\n"
                "print({{'reference': example['label'], 'predicted': ranked['top_label'], 'ranked_scores': [(e['label'], round(e['score'], 3)) for e in ranked['labels']]}})\n\n"
                "demo_labels = ['travel', 'cooking', 'dancing']\n"
                "texts = ['one day I will see the world', 'Whisk the eggs and fold in the flour before baking.', 'The tango class meets every Thursday evening.']\n"
                "expected = ['travel', 'cooking', 'dancing']\n"
                "text_ids = [f't{{index + 1}}' for index in range(len(texts))]\n"
                "ceilings = {{'MAX_TEXT_CHARS': MAX_TEXT_CHARS, 'MAX_TEXT_TOKENS': MAX_TEXT_TOKENS, 'MAX_LABELS': MAX_LABELS, 'MAX_LABEL_CHARS': MAX_LABEL_CHARS, 'HYPOTHESIS_TEMPLATE': HYPOTHESIS_TEMPLATE, 'NUM_NLI_LABELS': NUM_NLI_LABELS, 'ENTAILMENT_INDEX': ENTAILMENT_INDEX, 'CONTRADICTION_INDEX': CONTRADICTION_INDEX}}\n"
                "print(ceilings)\n"
                "print({{'decision_rules': {{'single': DECISION_RULE_SINGLE, 'multi': DECISION_RULE_MULTI}}}})\n"
                "input_manifest = validate_inputs(texts, demo_labels, multi_label=MULTI_LABEL, names=text_ids)\n"
                "try:\n"
                "    validate_inputs(texts, [*demo_labels, demo_labels[0]], multi_label=MULTI_LABEL)\n"
                "except ValueError as exc:\n"
                "    input_manifest['findings'].append({{'input': 'duplicate-label-probe', 'verdict': 'rejected', 'message': str(exc)}})\n"
                "with open('outputs/{stem}_input_manifest.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(input_manifest, handle, indent=2, ensure_ascii=False)\n"
                "results = []\n"
                "for text_id, text in zip(text_ids, texts, strict=True):\n"
                "    started = time.perf_counter()\n"
                "    result = pipe.classify(text, demo_labels, multi_label=MULTI_LABEL)\n"
                "    elapsed = time.perf_counter() - started\n"
                "    results.append(result)\n"
                "    scores = [entry['score'] for entry in result['labels']]\n"
                "    checks = {{\n"
                "        'one_entry_per_label': sorted(entry['label'] for entry in result['labels']) == sorted(demo_labels),\n"
                "        'scores_descending': all(a >= b for a, b in zip(scores, scores[1:], strict=False)),\n"
                "        'scores_in_unit_interval': all(0.0 <= s <= 1.0 for s in scores),\n"
                "        'single_label_scores_sum_to_one': MULTI_LABEL or abs(sum(scores) - 1.0) < 1e-6,\n"
                "        'top_label_is_first': result['top_label'] == result['labels'][0]['label'],\n"
                "        'n_tokens_within_ceiling': 1 <= result['n_tokens'] <= MAX_TEXT_TOKENS,\n"
                "    }}\n"
                "    if not all(checks.values()):\n"
                "        raise RuntimeError(f'classify output for {{text_id}} failed a sanity check: {{checks}}')\n"
                "    print({{'id': text_id, 'text': text[:60], 'top_label': result['top_label'], 'scores': {{e['label']: round(e['score'], 4) for e in result['labels']}}, 'seconds': round(elapsed, 3), 'n_tokens': result['n_tokens']}})\n"
                "other_mode = pipe.classify(texts[0], demo_labels, multi_label=not MULTI_LABEL)\n"
                "print({{'first_text_other_mode': {{'multi_label': other_mode['multi_label'], 'scores': {{e['label']: round(e['score'], 4) for e in other_mode['labels']}}}}}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the reference description should carry the largest entailment logit; the other "
                "description is usually pushed towards contradiction, but a related one can sit at neutral. The ranked "
                "single-label scores sum to one; in the other score mode the three synthetic scores no longer sum to one. "
                "Neither mode's scores are calibrated probabilities.\n\n"
                "<details><summary>Worked interpretation</summary>A high single-label score means \"more entailment "
                "evidence than for the other supplied descriptions\", not \"probably correct\": add an irrelevant category "
                "or remove the right one and the winner still receives most of the score mass. That is why a classifier "
                "that must pick a category cannot tell you that none applies.</details>\n\n"
                "## 6. Establish a baseline, then run the pretrained model\n\n"
                "**Question:** how much does the pretrained zero-shot model know about these ten categories before any "
                "task training? A number alone cannot answer that, so it is compared with a **majority-class baseline**: "
                "a rule that ignores the text and always predicts the most frequent category among the **training** "
                "labels. The training split is balanced, so all ten categories tie; the documented rule picks the "
                "alphabetically first description, and on the balanced test split the baseline scores exactly 10 %. Both "
                "systems are scored on the 200 test messages over the full ten-category vocabulary.\n\n"
                "**Metrics.** *Accuracy* is the share of messages whose predicted category equals the reference. For each "
                "category, *precision* = TP / (TP + FP), *recall* = TP / (TP + FN) and *F1* = 2TP / (2TP + FP + FN). "
                "**macro-F1** averages F1 over the ten categories with equal weight, so a category the model never gets "
                "right pulls the average down even when it is rare — which is why it complements accuracy when categories "
                "differ in frequency or difficulty. A category that is never predicted has **undefined precision**; it is "
                "reported as 0 with a note, never as a perfect score. A **confusion matrix** counts, for each reference "
                "category (row), which category was predicted (column).\n\n"
                "**Predict before running:** will the pretrained model beat 10 %? Which two descriptions from Section 4 "
                "will it confuse?"
            ),
            "code": (
                "baseline_majority = majority_baseline(test_records, train=train_records, labels=labels)\n"
                "print({{'majority_baseline': {{'accuracy': round(baseline_majority['accuracy'], 2), 'macro_f1': round(baseline_majority['macro_f1'], 2), 'n': baseline_majority['n'], 'rule': baseline_majority['baseline'], 'fitted_on': baseline_majority['fitted_on'], 'tie_rule': baseline_majority['tie_rule']}}}})\n"
                "t0 = time.perf_counter()\n"
                "frozen_test = pipe.evaluate(test_records, labels, hypothesis_template=TEMPLATE)\n"
                "print({{'pretrained_test': {{'accuracy': round(frozen_test['accuracy'], 2), 'macro_f1': round(frozen_test['macro_f1'], 2), 'n': frozen_test['n'], 'n_labels': frozen_test['n_labels'], 'verdict': frozen_test['verdict']}}, 'seconds': round(time.perf_counter() - t0, 1)}})\n"
                "print({{'longest_pair_tokens_scored': max(p['n_tokens'] for p in frozen_test['predictions']), 'inference_ceiling': MAX_TEXT_TOKENS, 'training_truncation': MAX_TRAIN_PAIR_TOKENS}})\n"
                "print(f\"{{'category':42}} support  precision  recall     F1\")\n"
                "for label, v in frozen_test['per_label'].items():\n"
                "    print(f\"{{label:42}} {{v['support']:7}} {{v['precision']:10.1f}} {{v['recall']:7.1f}} {{v['f1']:6.1f}}\" + ('  (' + v['note'] + ')' if v['note'] else ''))\n"
                "by_id = {{r['id']: r for r in test_records}}\n"
                "print('First four test messages, pretrained model (top three scores):')\n"
                "for p in frozen_test['predictions'][:4]:\n"
                "    top3 = sorted(p['scores'].items(), key=lambda kv: -kv[1])[:3]\n"
                "    print({{'text': by_id[p['id']]['text'][:80], 'reference': p['gold'], 'predicted': p['predicted'], 'top3': [(k, round(v, 3)) for k, v in top3]}})\n"
                "print(confusion_markdown(frozen_test, 'Pretrained model, test split (rows: reference; columns P1..P10 in the same order)'))\n"
                "print({{'pretrained_beats_majority': frozen_test['accuracy'] > baseline_majority['accuracy']}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the pretrained model sits far above the 10 % floor without seeing a single training "
                "message, but not uniformly: the per-class table and the confusion matrix show which descriptions it reads "
                "badly and where their messages go instead. Compare with your prediction.\n\n"
                "## 7. Adapt the model with labelled examples\n\n"
                "**Question:** does training on 400 labelled messages close the remaining gap on messages the model has "
                "not seen? After this step the model is **task-adapted, no longer zero-shot** for these ten categories.\n\n"
                "`pipe.adapt` turns every training message into two NLI pairs — (message, template(reference description)) "
                "labelled *entailment* and (message, template(a seeded wrong description)) labelled *contradiction* — and "
                "trains only the last `TRAINABLE_DECODER_LAYERS` decoder blocks plus the NLI classification head: two "
                "blocks by default, 34,646,019 of 407,344,131 parameters. The encoder, the shared embeddings and the "
                "earlier decoder blocks stay frozen. The budget is bounded and fixed before evaluation: cross-entropy over "
                "the three NLI logits, AdamW at a fixed learning rate, gradient clipping at 1.0, seeded shuffling, no "
                "scheduler, and pairs truncated to 256 tokens **during training only**.\n\n"
                "**Checkpoint selection uses validation evidence only.** Epoch 0 records the pretrained model's validation "
                "accuracy; after every epoch the validation split is scored with the same descriptions and template, and "
                "the epoch with the highest validation accuracy is kept (earliest wins a tie, and epoch 0 can win, in "
                "which case no training change is kept). The test split plays no part in this choice.\n\n"
                "**Predict before running:** will validation accuracy rise every epoch? Could adaptation make some "
                "category worse?"
            ),
            "code": (
                "EPOCHS = 2  # @param {{type:\"integer\"}}\n"
                "LEARNING_RATE = 2e-5  # @param {{type:\"number\"}}\n"
                "BATCH_SIZE = 16  # @param {{type:\"integer\"}}\n"
                "TRAINABLE_DECODER_LAYERS = 2  # @param {{type:\"integer\"}}\n\n"
                "def report(entry):\n"
                "    row = {{'epoch': entry['epoch'], 'train_loss': None if entry['train_loss'] is None else round(entry['train_loss'], 4)}}\n"
                "    if entry.get('val'):\n"
                "        row['val_accuracy'] = round(entry['val']['accuracy'], 2)\n"
                "        row['val_macro_f1'] = round(entry['val']['macro_f1'], 2)\n"
                "    if 'note' in entry:\n"
                "        row['note'] = entry['note']\n"
                "    print(row)\n\n"
                "t0 = time.perf_counter()\n"
                "adapt_result = pipe.adapt(train_records, val_records, labels=labels, epochs=EPOCHS, lr=LEARNING_RATE, batch_size=BATCH_SIZE, trainable_decoder_layers=TRAINABLE_DECODER_LAYERS, hypothesis_template=TEMPLATE, progress=report)\n"
                "adapt_seconds = round(time.perf_counter() - t0, 1)\n"
                "print({{'trainable_parameters': adapt_result['n_trainable'], 'total_parameters': adapt_result['n_total'], 'pairs_per_record': adapt_result['pairs_per_record'], 'best_epoch': adapt_result['best_epoch'], 'selection': adapt_result['selection'], 'seconds': adapt_seconds}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the training loss and the validation scores per epoch, and which epoch was kept. "
                "Training loss falling does not by itself mean better held-out performance.\n\n"
                "## 8. Compare the three systems on the same held-out messages\n\n"
                "The test split was never used for training or epoch selection, and no message in it appears in the "
                "training or validation splits. The majority baseline, the pretrained model and the selected adapted model "
                "are scored on the same 200 messages over the same ten categories. Two hundred messages from one seeded "
                "split of one corpus give **no dispersion estimate**: differences of a point or two are within what a "
                "different sample could change.\n\n"
                "**Predict before running:** by how much will adaptation change accuracy and macro-F1? Will any category "
                "get worse?"
            ),
            "code": (
                "adapted_test = pipe.evaluate(test_records, labels, hypothesis_template=TEMPLATE)\n"
                "adapted_val = pipe.evaluate(val_records, labels, hypothesis_template=TEMPLATE)\n"
                "comparison = {{\n"
                "    'accuracy': {{'majority': round(baseline_majority['accuracy'], 2), 'pretrained': round(frozen_test['accuracy'], 2), 'adapted': round(adapted_test['accuracy'], 2)}},\n"
                "    'macro_f1': {{'majority': round(baseline_majority['macro_f1'], 2), 'pretrained': round(frozen_test['macro_f1'], 2), 'adapted': round(adapted_test['macro_f1'], 2)}},\n"
                "    'delta_vs_frozen': {{'accuracy': round(adapted_test['accuracy'] - frozen_test['accuracy'], 2), 'macro_f1': round(adapted_test['macro_f1'] - frozen_test['macro_f1'], 2)}},\n"
                "    'per_label_f1': {{label: {{'majority': round(baseline_majority['per_label'][label]['f1'], 1), 'pretrained': round(frozen_test['per_label'][label]['f1'], 1), 'adapted': round(adapted_test['per_label'][label]['f1'], 1)}} for label in labels}},\n"
                "}}\n"
                "for metric in ('accuracy', 'macro_f1', 'delta_vs_frozen'):\n"
                "    print({{metric: comparison[metric]}})\n"
                "print(f\"{{'category':42}} support  majority  pretrained  adapted   (F1)\")\n"
                "for label in labels:\n"
                "    row = comparison['per_label_f1'][label]\n"
                "    print(f\"{{label:42}} {{adapted_test['per_label'][label]['support']:7}} {{row['majority']:9.1f}} {{row['pretrained']:11.1f}} {{row['adapted']:8.1f}}\")\n"
                "print(confusion_markdown(adapted_test, 'Adapted model, test split (rows: reference; columns P1..P10 in the same order)'))\n"
                "worse = [label for label in labels if comparison['per_label_f1'][label]['adapted'] < comparison['per_label_f1'][label]['pretrained']]\n"
                "print({{'adapted_beats_pretrained_accuracy': adapted_test['accuracy'] > frozen_test['accuracy'], 'categories_with_lower_f1_after_adaptation': worse}})\n"
                "evaluation_report_payload = {{\n"
                "    'model': {{'id': MODEL_ID, 'revision': MODEL_REVISION, 'key': MODEL_KEY}},\n"
                "    'data_source': data_source,\n"
                "    'dataset_digests': {{name: manifest['digest'] for name, manifest in dataset_manifests.items()}},\n"
                "    'splits': disjoint,\n"
                "    'categories': CATEGORIES,\n"
                "    'labels': labels,\n"
                "    'hypothesis_template': TEMPLATE,\n"
                "    'baselines': {{'majority': baseline_majority}},\n"
                "    'frozen_test': frozen_test,\n"
                "    'validation_metrics': adapted_val,\n"
                "    'test_metrics': adapted_test,\n"
                "    'comparison': comparison,\n"
                "    'adaptation': {{k: v for k, v in adapt_result.items() if k not in ('history', 'trainable_names')}},\n"
                "    'history': adapt_result['history'],\n"
                "    'adaptation_seconds': adapt_seconds,\n"
                "}}\n"
                "with open('outputs/{stem}_evaluation_report.json', 'w', encoding='utf-8') as f:\n"
                "    json.dump(evaluation_report_payload, f, indent=2, ensure_ascii=False)\n"
                "print({{'report': 'outputs/{stem}_evaluation_report.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** the three rows of the comparison, the categories that gained most, any category "
                "whose F1 fell, and how the confusion matrix changed. A negative or flat result is still a result: it is "
                "reported, not hidden, and the notebook does not stop on it.\n\n"
                "## 9. Interpret paired changes on the same messages\n\n"
                "Aggregate scores hide individual changes. Because both models scored the same test messages, each message "
                "falls into one group: **corrected** (pretrained wrong, adapted right), **new error** (pretrained right, "
                "adapted wrong), **unchanged correct**, **unchanged incorrect**, or wrong in both with a different wrong "
                "answer. **Example-selection rule:** for each group the cell prints up to three messages in test-split "
                "order (the seeded order), so the examples are not chosen by looking at their scores. If a group is empty, "
                "the cell says so."
            ),
            "code": (
                "pretrained_by_id = {{p['id']: p for p in frozen_test['predictions']}}\n"
                "adapted_by_id = {{p['id']: p for p in adapted_test['predictions']}}\n"
                "test_ids = [r['id'] for r in test_records]\n"
                "adaptation_changes = paired_changes(test_ids, [r['label'] for r in test_records], [pretrained_by_id[i]['predicted'] for i in test_ids], [adapted_by_id[i]['predicted'] for i in test_ids])\n"
                "print({{'paired_counts': adaptation_changes['counts'], 'changed_predictions': adaptation_changes['changed_predictions']}})\n"
                "for group in ('corrected', 'new_error', 'unchanged_incorrect'):\n"
                "    members = adaptation_changes['ids'][group][:3]\n"
                "    print(f'--- {{group}}: showing {{len(members)}} of {{len(adaptation_changes[\"ids\"][group])}}' + ('' if members else ' (none in this run)'))\n"
                "    for item in members:\n"
                "        before, after = pretrained_by_id[item], adapted_by_id[item]\n"
                "        print({{'text': by_id[item]['text'][:90], 'reference': before['gold'], 'pretrained': (before['predicted'], round(before['score'], 3)), 'adapted': (after['predicted'], round(after['score'], 3))}})"
            ),
        },
        {
            "md": (
                "<details><summary>Interpretation hint</summary>Corrected messages often belong to the categories the "
                "pretrained model read badly: adaptation taught it what these annotators mean by those descriptions. New "
                "errors, if any, show that adaptation trades some cases for others. Unchanged errors are candidates for "
                "ambiguous or mislabelled messages — read them before blaming the model.</details>\n\n"
                "## 10. Change one thing: the category wording\n\n"
                "**Question: how sensitive are predictions to equivalent descriptions of the same categories?** Two fixed "
                "description sets are compared: **A — Original**, the canonical descriptions used everywhere else, and **B "
                "— Paraphrased**, reviewed descriptions intended to keep each category's meaning and scope while changing "
                "its words (`LABEL_SET_PARAPHRASED` in the carried code).\n\n"
                "**Only the wording changes.** Kept constant: the category IDs, their order and count; the 100 validation "
                "messages (10 per category) and their reference labels; the **pretrained** checkpoint, freshly loaded and "
                "verified from the same snapshot so that adaptation does not confound the comparison; the hypothesis "
                "template; and tokenisation and scoring settings (single-label, argmax). Each prediction is mapped back to "
                "its stable category ID before comparing, so a paraphrase can never change a reference label.\n\n"
                "**Evaluation boundaries.** This is an exploratory activity on validation messages: the canonical test "
                "results in Section 8 used set A and are not replaced. Choosing a wording because it scores better here "
                "would be a new configuration that needs its own frozen evaluation; one paraphrase set cannot establish "
                "general robustness to wording; and changing a category's scope or making categories overlap is a "
                "different experiment.\n\n"
                "**Predict before running (write it down):** how many of the 100 predictions will change? Which "
                "categories' paraphrases are most likely to move the model, and in which direction?"
            ),
            "code": (
                "if USE_BYOD:\n"
                "    wording_activity = {{'skipped': 'BYOD has no reviewed second description set; supply one to run this activity'}}\n"
                "    print(wording_activity)\n"
                "else:\n"
                "    base_pipe = BARTZeroShotClassificationPipeline.from_pretrained(weights_dir=WEIGHTS_DIR)\n"
                "    if base_pipe.adapter is not None:\n"
                "        raise RuntimeError('the wording activity must use the pretrained checkpoint')\n"
                "    DESCRIPTION_SETS = {{'A': dict(LABEL_SET), 'B': dict(LABEL_SET_PARAPHRASED)}}\n"
                "    category_ids = list(LABEL_SET)\n"
                "    if list(DESCRIPTION_SETS['B']) != category_ids:\n"
                "        raise RuntimeError('description set B must cover the same category IDs in the same order')\n"
                "    print(f\"{{'category ID':38}} {{'A — original':42}} B — paraphrased\")\n"
                "    for intent in category_ids:\n"
                "        print(f\"{{intent:38}} {{DESCRIPTION_SETS['A'][intent]:42}} {{DESCRIPTION_SETS['B'][intent]}}\")\n"
                "    activity_ids = [r['id'] for r in val_records]\n"
                "    gold_ids = [r['intent'] for r in val_records]\n"
                "    set_results, predicted_ids = {{}}, {{}}\n"
                "    for name, descriptions in DESCRIPTION_SETS.items():\n"
                "        records_for_set = [{{**r, 'label': descriptions[r['intent']]}} for r in val_records]\n"
                "        result = base_pipe.evaluate(records_for_set, [descriptions[i] for i in category_ids], hypothesis_template=TEMPLATE)\n"
                "        to_id = {{description: intent for intent, description in descriptions.items()}}\n"
                "        predicted_ids[name] = [to_id[p['predicted']] for p in result['predictions']]\n"
                "        set_results[name] = result\n"
                "        print({{'description_set': name, 'accuracy': round(result['accuracy'], 2), 'macro_f1': round(result['macro_f1'], 2), 'n': result['n']}})\n"
                "    wording_changes = paired_changes(activity_ids, gold_ids, predicted_ids['A'], predicted_ids['B'])\n"
                "    print({{'changed_predictions': wording_changes['changed_predictions'], 'changed_fraction': round(wording_changes['changed_fraction'], 3), 'correct_to_incorrect': wording_changes['counts']['new_error'], 'incorrect_to_correct': wording_changes['counts']['corrected'], 'incorrect_to_other_incorrect': wording_changes['counts']['changed_incorrect_to_incorrect']}})\n"
                "    scores_by_set = {{name: {{p['id']: p for p in result['predictions']}} for name, result in set_results.items()}}\n"
                "    changed = [i for i, a, b in zip(activity_ids, predicted_ids['A'], predicted_ids['B'], strict=True) if a != b]\n"
                "    print(f'Changed examples (up to four, in validation-split order; {{len(changed)}} changed in total):' if changed else 'No prediction changed between the two description sets.')\n"
                "    val_by_id = {{r['id']: r for r in val_records}}\n"
                "    for item in changed[:4]:\n"
                "        a, b = scores_by_set['A'][item], scores_by_set['B'][item]\n"
                "        print({{'text': val_by_id[item]['text'][:90], 'reference_id': val_by_id[item]['intent'], 'A': (a['predicted'], round(a['score'], 3)), 'B': (b['predicted'], round(b['score'], 3))}})\n"
                "    wording_activity = {{\n"
                "        'question': 'How sensitive are predictions to equivalent descriptions of the same categories?',\n"
                "        'checkpoint': {{'model_id': MODEL_ID, 'model_revision': MODEL_REVISION, 'state': 'pretrained (not adapted), reloaded from the verified snapshot'}},\n"
                "        'split': 'validation', 'n': len(activity_ids), 'hypothesis_template': TEMPLATE, 'multi_label': False,\n"
                "        'category_ids': category_ids, 'description_sets': DESCRIPTION_SETS,\n"
                "        'metrics': {{name: {{'accuracy': r['accuracy'], 'macro_f1': r['macro_f1'], 'per_label': r['per_label'], 'confusion': r['confusion']}} for name, r in set_results.items()}},\n"
                "        'paired_changes': wording_changes,\n"
                "        'predictions': {{name: [{{'id': p['id'], 'predicted': p['predicted'], 'score': p['score'], 'scores': p['scores']}} for p in r['predictions']] for name, r in set_results.items()}},\n"
                "        'boundaries': 'exploratory validation activity; canonical test reporting uses set A only; one paraphrase set does not establish general robustness',\n"
                "    }}\n"
                "    del base_pipe\n"
                "with open('outputs/{stem}_description_activity.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(wording_activity, handle, indent=2, ensure_ascii=False)\n"
                "print({{'activity_record': 'outputs/{stem}_description_activity.json'}})"
            ),
        },
        {
            "md": (
                "**What to notice:** compare the changed count with your prediction, and read the direction of each "
                "change: correct→incorrect, incorrect→correct, or one wrong answer for another. Look at which categories' "
                "scores moved and whether the paraphrase really kept the meaning.\n\n"
                "<details><summary>Interpretation hint</summary>Even meaning-preserving paraphrases change the hypothesis "
                "text the NLI model reads, so some predictions usually move; the model has no notion that two phrases name "
                "the same category. A similar overall accuracy can hide many individual changes in both directions, which "
                "is why the paired counts matter. The result describes these two wordings on these 100 messages — not the "
                "model's robustness to wording in general — and choosing set B because it scores higher here would require "
                "a new, separately frozen test evaluation.</details>\n\n"
                "## 11. Export and reload the adapted model\n\n"
                "Ten messages that were in none of the splits (one per category, drawn from the training file beyond the "
                "sample) are classified by the adapted model through the same `classify` contract and scored with the "
                "batch `evaluation_report` — a `sample-sanity` observation on ten items, never a benchmark — and with "
                "`pipe.evaluate` (`measured-small-sample`).\n\n"
                "`pipe.save_artifact` writes the trained tensors — the last two decoder blocks and the NLI head, about 139 "
                "MB — as `adapter.safetensors`, with a `manifest.json` recording the artifact format, the base model id and "
                "revision, the digest of the base `model.safetensors`, the tensor names, the file size and SHA-256, the "
                "training configuration and the epoch history. The classification setup travels with it in the manifest "
                "metadata: the stable category IDs and descriptions, the hypothesis template and the scoring configuration, "
                "so the same classifier can be rebuilt later. "
                "`BARTZeroShotClassificationPipeline.from_artifact` re-verifies the base snapshot, checks the artifact "
                "manifest and digest **before** deserialising, refuses any tensor that is not an adaptable decoder or head "
                "tensor, and overlays the tensors onto a freshly loaded base: a new pipeline object built from the saved "
                "files, not the in-memory model. It then rescores all 200 test messages; the cell requires identical "
                "predictions, score differences within 1e-5 and identical metrics. **Reload parity verifies that the saved "
                "behaviour is reproduced, not that the behaviour is good** — a saved model reproduces its errors exactly."
            ),
            "code": (
                "import csv\n"
                "import shutil\n\n"
                "if USE_BYOD:\n"
                "    new_records = [{{**r, 'id': f'new-{{i:02d}}'}} for i, r in enumerate(test_records[:10])]\n"
                "else:\n"
                "    used = {{r['text'].lower() for part in splits.values() for r in part}}\n"
                "    spare = [r for r in filter_records(corpus['train']) if r['text'].lower() not in used]\n"
                "    new_records = [{{**next(r for r in spare if r['label'] == label), 'id': f'new-{{i:02d}}'}} for i, label in enumerate(labels)]\n"
                "new_results = [pipe.classify(r['text'], labels, hypothesis_template=TEMPLATE) for r in new_records]\n"
                "new_report = evaluation_report(new_results, [r['label'] for r in new_records], sample_kind='ten unseen Banking77 messages' if not USE_BYOD else 'BYOD test records')\n"
                "new_metrics = pipe.evaluate(new_records, labels, hypothesis_template=TEMPLATE)\n"
                "for record, item in zip(new_records, new_results, strict=True):\n"
                "    print({{'id': record['id'], 'text': record['text'][:70], 'adapted': item['top_label'], 'score': round(item['labels'][0]['score'], 3), 'gold': record['label']}})\n"
                "print({{'new_messages': {{'verdict': new_report['verdict'], 'accuracy': new_report['metrics'][0]['value'], 'reason': new_report['reason']}}, 'evaluate_verdict': new_metrics['verdict'], 'macro_f1': round(new_metrics['macro_f1'], 2)}})\n"
                "with open('outputs/{stem}_predictions.csv', 'w', encoding='utf-8', newline='') as handle:\n"
                "    writer = csv.DictWriter(handle, fieldnames=['id', 'text', 'top_label', 'score', 'gold', 'n_tokens'])\n"
                "    writer.writeheader()\n"
                "    for record, item in zip(new_records, new_results, strict=True):\n"
                "        writer.writerow({{'id': record['id'], 'text': record['text'], 'top_label': item['top_label'], 'score': item['labels'][0]['score'], 'gold': record['label'], 'n_tokens': item['n_tokens']}})\n\n"
                "classification_setup = {{\n"
                "    'categories': CATEGORIES,\n"
                "    'hypothesis_template': TEMPLATE,\n"
                "    'scoring': {{'multi_label': False, 'decision_rule': DECISION_RULE_SINGLE, 'label_order': labels, 'max_text_tokens': MAX_TEXT_TOKENS, 'training_truncation_tokens': MAX_TRAIN_PAIR_TOKENS}},\n"
                "}}\n"
                "artifact_dir = Path('outputs/{stem}_adapter')\n"
                "shutil.rmtree(artifact_dir, ignore_errors=True)\n"
                "pipe.save_artifact(artifact_dir, metadata={{'tutorial': '{stem}', 'data_source': data_source, 'classification_setup': classification_setup}})\n"
                "artifact_manifest = json.loads((artifact_dir / 'manifest.json').read_text(encoding='utf-8'))\n"
                "print({{'artifact': str(artifact_dir), 'format': artifact_manifest['format'], 'tensors': len(artifact_manifest['tensors']), 'bytes': artifact_manifest['files'][0]['bytes'], 'sha256': artifact_manifest['files'][0]['sha256'][:16] + '...', 'categories_recorded': len(artifact_manifest['metadata']['classification_setup']['categories'])}})\n\n"
                "reloaded = BARTZeroShotClassificationPipeline.from_artifact(artifact_dir, weights_dir=WEIGHTS_DIR, device=pipe.device)\n"
                "reloaded_test = reloaded.evaluate(test_records, labels, hypothesis_template=TEMPLATE)\n"
                "score_delta = max(abs(a['scores'][label] - b['scores'][label]) for a, b in zip(adapted_test['predictions'], reloaded_test['predictions'], strict=True) for label in labels)\n"
                "parity = {{\n"
                "    'identical_labels': sum(a['predicted'] == b['predicted'] for a, b in zip(adapted_test['predictions'], reloaded_test['predictions'], strict=True)),\n"
                "    'of': len(test_records),\n"
                "    'max_score_difference': score_delta,\n"
                "    'score_tolerance': 1e-5,\n"
                "    'metrics_identical': (reloaded_test['accuracy'], reloaded_test['macro_f1']) == (adapted_test['accuracy'], adapted_test['macro_f1']),\n"
                "    'boundary': 'new pipeline object built from the saved files in this kernel process',\n"
                "}}\n"
                "print({{'reload_parity': parity, 'reloaded_best_epoch': reloaded.adapter['best_epoch']}})\n"
                "assert parity['identical_labels'] == parity['of'] and score_delta <= parity['score_tolerance'] and parity['metrics_identical']\n\n"
                "weight_entry = next(entry for entry in snapshot['files'] if entry['path'] == WEIGHT_FILE)\n"
                "result_payload = {{\n"
                "    'notebook_source': NOTEBOOK_SOURCE,\n"
                "    'repository_revision': NOTEBOOK_SOURCE['repository_revision'],\n"
                "    'model_id': MODEL_ID,\n"
                "    'model_revision': MODEL_REVISION,\n"
                "    'model_license': MODEL_LICENSE,\n"
                "    'snapshot': {{'path': str(WEIGHTS_DIR), 'files': len(snapshot['files']), 'total_bytes': snapshot.get('totalBytes'), 'fetched_this_run': fetched, 'weight_file': WEIGHT_FILE, 'weight_format': 'safetensors, digest-verified', 'weight_sha256': weight_entry['sha256']}},\n"
                "    'data_source': data_source,\n"
                "    'corpus': {{'name': CORPUS_NAME, 'release': CORPUS_RELEASE, 'base_url': CORPUS_BASE_URL, 'files': {{k: {{'name': v[0], 'bytes': v[1], 'sha256': v[2]}} for k, v in CORPUS_FILES.items()}}, 'license': CORPUS_LICENSE, 'label_set': LABEL_SET}},\n"
                "    'inference_contract': {{'input_manifest': input_manifest, 'demo_results': [{{'id': i, 'top_label': r['top_label'], 'scores': {{e['label']: e['score'] for e in r['labels']}}, 'n_tokens': r['n_tokens'], 'decision_rule': r['decision_rule']}} for i, r in zip(text_ids, results, strict=True)], 'expected': expected}},\n"
                "    'classification_setup': classification_setup,\n"
                "    'labels': labels,\n"
                "    'hypothesis_template': TEMPLATE,\n"
                "    'comparison': comparison,\n"
                "    'adaptation_paired_changes': adaptation_changes['counts'],\n"
                "    'wording_activity': {{k: wording_activity[k] for k in ('checkpoint', 'split', 'n', 'paired_changes') if k in wording_activity}} if 'skipped' not in wording_activity else wording_activity,\n"
                "    'new_messages': new_report,\n"
                "    'artifact': {{'dir': str(artifact_dir), 'sha256': artifact_manifest['files'][0]['sha256'], 'bytes': artifact_manifest['files'][0]['bytes'], 'tensors': len(artifact_manifest['tensors'])}},\n"
                "    'reload_parity': parity,\n"
                "    'runtime': {{'python': platform.python_version(), 'torch': torch.__version__, 'transformers': transformers.__version__, 'device': pipe.device, 'dtype': 'float32', 'source': pipe.source}},\n"
                "}}\n"
                "with open('outputs/{stem}_result.json', 'w', encoding='utf-8') as handle:\n"
                "    json.dump(result_payload, handle, indent=2, ensure_ascii=False)\n"
                "print(sorted(os.listdir('outputs')))"
            ),
        },
    ],
    "closing": (
        "## Interpretation and limits\n\n"
        "**Conclude with evidence.** Write a short conclusion from your own run using this scaffold (an optional personal "
        "note, not a required submission):\n\n"
        "> On [dataset and split], the pretrained classifier achieved [accuracy / macro-F1], compared with [the majority "
        "baseline] and [the adapted model]. Rephrasing category descriptions changed [count / proportion] predictions on "
        "the validation activity, including [a specific observation]. These results suggest [a bounded conclusion], but do "
        "not establish [a broader claim].\n\n"
        "**What this evidence supports.** The pretrained NLI model classifies these ten banking categories well above the "
        "majority floor using only their descriptions; a bounded adaptation of the last two decoder blocks and the NLI head "
        "on 800 entailment/contradiction pairs changes the held-out results in the direction and by the amount your run "
        "reports; the category wording is part of the input and changing it changes individual predictions; and the "
        "exported adapter reproduces the adapted model's predictions after reload.\n\n"
        "**What it does not establish.** The test split is 200 messages over ten balanced categories from one seeded split "
        "of one corpus, with no dispersion estimate; the metrics are exact-match accuracy and macro-F1, neither a "
        "calibration measure, and the scores remain entailment-derived softmaxes. Banking77 messages are short, English "
        "and single-intent. Nothing here shows that the adapted model is better on your categories, that it separates "
        "overlapping categories, that it recognises messages belonging to none of the supplied categories (any such "
        "demonstration you try is qualitative unless you build an explicit unknown-category evaluation), or that one "
        "paraphrase set measures robustness to wording in general. Adapting towards ten descriptions and one template "
        "also changes the model's behaviour on other label sets, and nothing here measures that. \"Zero-shot\" describes "
        "this notebook's task-training condition; it does not mean the model never saw related text in pretraining.\n\n"
        "**Carry to real data.** Read the majority baseline and the pretrained model on *your* categories, descriptions "
        "and template before any adapted number — wording moves zero-shot scores. De-duplicate texts across splits and "
        "split by customer or conversation when several messages come from one. Keep baseline fitting and adaptation on "
        "training data, choose checkpoints and wordings on validation data, and report test data once for a frozen "
        "configuration.\n\n"
        "**Optional experiments (they do not affect the default path):** set `TRAINABLE_DECODER_LAYERS = 1` and compare "
        "artifact size and test scores; change `TEMPLATE` (for example `This message is about {{}}.`) and watch the "
        "pretrained per-class F1 move before any training; set `MULTI_LABEL = True` in Section 5 and read the independent "
        "scores; or bring your own labelled messages through BYOD (Section 4) and read the majority baseline before the "
        "adapted number.\n\n"
        "**Bring your own data.** Supply texts, a category vocabulary in which each description is short, readable and used "
        "identically across records (in this contract the description is also the category's stable ID), and a reference "
        "label per text; the notebook then creates separate training, validation and test roles. Without reference labels, "
        "use `classify` on your texts for qualitative exploration only — no accuracy or F1 can be reported. Only upload "
        "data you are permitted to process in a hosted runtime; files stay in this runtime and are not published by the "
        "notebook.\n\n"
        "Successful execution proves that the recorded repository revision's pipeline modules, carried in this standalone "
        "notebook, can acquire and digest-verify the pinned model snapshot, fetch and digest-verify a real labelled corpus, "
        "validate the demonstrated dataset contract without leakage, execute the inference contract, a training-fitted "
        "baseline, a bounded fine-tuning and a controlled wording comparison, evaluate on an independent split, and emit "
        "the shown machine-readable artifacts — without the repository being reachable. It does **not** establish benchmark "
        "superiority, classification quality on any other label set, a calibrated score or acceptance threshold, "
        "unknown-category rejection, or production fitness.\n\n"
        "**AI Assistance Disclosure:** This notebook's code and explanations were developed with generative AI assistance "
        "under maintainer direction. The maintainer remains responsible for reviewing the implementation, validating "
        "results and making release decisions. AI assistance does not constitute independent verification, provider "
        "endorsement or release approval.\n\n"
        "## References\n\n"
        "- Repository README: https://github.com/kurtvalcorza/bart-mnli-zero-shot-classification-pipeline/blob/main/README.md\n"
        "- Repository model card: https://github.com/kurtvalcorza/bart-mnli-zero-shot-classification-pipeline/blob/main/MODEL_CARD.md\n"
        "- Weight provenance: https://github.com/kurtvalcorza/bart-mnli-zero-shot-classification-pipeline/blob/main/docs/WEIGHTS.md\n"
        "- Upstream model: https://huggingface.co/{MODEL_ID}\n"
        "- Upstream code: https://github.com/facebookresearch/fairseq/tree/main/examples/bart\n"
        "- BART: Denoising Sequence-to-Sequence Pre-training for Natural Language Generation, Translation, and Comprehension (Lewis et al., 2019): https://arxiv.org/abs/1910.13461\n"
        "- Benchmarking Zero-shot Text Classification: Datasets, Evaluation and Entailment Approach (Yin et al., EMNLP 2019): https://arxiv.org/abs/1909.00161\n"
        "- Efficient Intent Detection with Dual Sentence Encoders (Casanueva et al., 2020; Banking77, CC BY 4.0): https://arxiv.org/abs/2003.04807\n"
        "- DIMER Notebook Specification 2.2 and Model Card Specification (fleet specs in the ml-worker repository): https://github.com/kurtvalcorza/ml-worker/blob/main/integrations/dimer/fleet-specs/NOTEBOOK_SPEC.md"
    ),
}
